### ISSUE TITLE
Swapping via 1inch Safe app executes a SignMessage transaction

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#155]
### Issue Category

Other

### What happened?

User swapped assets via 1inch safe app, swap was successful but message type was "signMessage" and the assets are still the same. User tried swapping via Cowswap safe app and swap was successful, also successfully received the assets. 

![image](https://user-images.githubusercontent.com/114049495/224475795-4fec41b5-4e29-49ca-a9fc-127080909d4b.png)

### Date and time this happened or you first noticed this issue

11-03-2023

### Network

Ethereum Mainnet

### Safe Address

0xE8eB13468De89b3d6159d095d9c351C8054c9bBB

### Token Type

None

### Transactions

```shell
Successful transaction when swapping via 1inch safe app https://etherscan.io/tx/0x7798c4302769374734ceafcaa5d7c5551e05878982314fa65539d7452b4324f1
```

**Comment by katspaugh** [comment]
@dasanra @JagoFigueroa do you guys have any alpha on the 1inch Safe App, is this something new?

**Comment by mikhailxyz** [comment]
Perhaps related to the fusion upgrade https://help.1inch.io/en/articles/6796085-what-is-1inch-fusion-and-how-does-it-work#h_202f7cf31d - it now should work in a similar way as cowswap. It'd be good to test if orders are executed since signing a message for an off-chain order is totally expected. Nevertheless, I reported the bug to the 1inch team in our telegram channel

**Comment by katspaugh** [comment]
FWIW, when I did a couple swaps, it made regular transactions (tested on Eth and Polygon), and it routed me to Uniswap and its own pool, respectively.
<img width="623" alt="Screenshot 2023-03-14 at 16 00 11" src="https://user-images.githubusercontent.com/381895/225042847-3c564f8e-f981-4b59-8138-a429e06fec16.png">

**Comment by katspaugh** [comment]
OK, maybe a mistake on the user's behalf. Since they sat the swap was actually successful.

That signMessage might be from another app, esp. given the order of transactions:
<img width="414" alt="Screenshot 2023-03-14 at 16 13 41" src="https://user-images.githubusercontent.com/381895/225047001-a14d5114-1921-40b6-b644-353bed0a677f.png">

Closing.
