### ISSUE TITLE
HTTP 500 error when user submits signature

### ISSUE THREAD

**Issue by CindyLo0** [5afe/safe-support#167]
### Issue Category

Other

### What happened?

1. User attempts to sign a transaction 
2. Tenderly Simulation is successful 
3. User submits and signs with their connected MetaMask wallet
4. An error pops up, please see screenshot
![image](https://user-images.githubusercontent.com/79137197/230632028-b488ad2d-8928-4eec-817d-1fd3ffff5187.png)
5. Error in dev console: 
![image](https://user-images.githubusercontent.com/79137197/230632047-a512f865-0913-45cd-b1bc-72ae2d731651.png)

### Date and time this happened or you first noticed this issue

07/04/2023 17:00

### Network

Arbitrum

### Safe Address

0x63B7448D9695Bb595833C9fCd5B3bB5E56F36864

### Token Type

None

**Comment by jonwalch** [comment]
Hi I'm the user that ran into this issue. Here's context:

1. EOA submits some transaction with nonce X
2. Signers now want to cancel that tx. Contract signer calls approveHash() on a 0Ξ transfer with nonce X to cancel step 1
3. First EOA signer can sign the 0Ξ transfer through the Gnosis UI Replace Transaction flow
4. Second EOA signer cannot sign the 0Ξ transfer and gets HTTP 500

I do believe this is a backend issue, due to the HTTP 500 - Internal Server Error.

**Comment by DiogoSoaress** [comment]
Hi @jonwalch I was just trying to reproduce the error you got based on the latest reproduction steps provided.

Context: I have a 3/4 Safe where one of the owners is another Safe -> https://app.safe.global/transactions/queue?safe=gor:0xd97A567d14c8fe25C8023A19438756D0D0d52483

Steps I took:
1. Created a "Send funds" transaction from an EOA owner.
2. Collected another signature from another EOA owner.
3. Created a "Reject transaction" for the previous steps transaction.
4. Signed with one of the EOA owners
5. Signed with another EOA owner

I didn't receive any `HTTP 500` on signing with the second EOA. Did I miss something? Also, are you persistently receiving the 500?

Do you mind clarifying what you mean by a  `0Ξ transfer` ? I assumed it's a "Rejection transaction" but want to be sure.

![Screenshot 2023-04-13 at 19 05 45](https://user-images.githubusercontent.com/32431609/231833228-024e5af0-5c63-4e7e-854e-f2bc97db14bb.png)

**Comment by DiogoSoaress** [comment]
Please be aware that any signature from a SC has to be onchain to be picked by our backend.

**Comment by jonwalch** [comment]
The approveHash() call happened onchain through our smart contract. Or am I misunderstanding?

**Comment by Uxio0** [comment]
It would be very useful that aside from the images you provide the JSON payloads so we can try to reproduce

**Comment by jonwalch** [comment]
Request URL: https://safe-client.safe.global/v1/chains/42161/transactions/0x63B7448D9695Bb595833C9fCd5B3bB5E56F36864/propose
Request Method: POST
Status Code: 500 
Remote Address: 18.238.4.19:443
Referrer Policy: strict-origin-when-cross-origin

Response Headers:
access-control-allow-credentials: true
access-control-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
access-control-allow-methods: OPTIONS, GET, HEAD
access-control-allow-origin: *
access-control-max-age: 1728000
content-length: 183
content-type: application/json
date: Fri, 14 Apr 2023 13:42:23 GMT
permissions-policy: interest-cohort=()
via: 1.1 4ac9029cca7343b507846071d1d5dbc8.cloudfront.net (CloudFront)
x-amz-cf-id: xW0YMsA5fonZ22a4s_HZHcOADxNSt0cH7TZWnAxaFD4KxEdLr_sbaA==
x-amz-cf-pop: PHL51-P1
x-cache: Error from cloudfront
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN

Request Headers:
:authority: safe-client.safe.global
:method: POST
:path: /v1/chains/42161/transactions/0x63B7448D9695Bb595833C9fCd5B3bB5E56F36864/propose
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 807
content-type: application/json
origin: https://app.safe.global
referer: https://app.safe.global/
sec-ch-ua: "Chromium";v="112", "Brave";v="112", "Not:A-Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
sec-gpc: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

{
	"to": "0x63B7448D9695Bb595833C9fCd5B3bB5E56F36864",
	"value": "0",
	"data": "0x",
	"operation": 0,
	"baseGas": "0",
	"gasPrice": "0",
	"gasToken": "0x0000000000000000000000000000000000000000",
	"refundReceiver": "0x0000000000000000000000000000000000000000",
	"nonce": "2",
	"safeTxGas": "0",
	"safeTxHash": "0xf24b2f9dc370cb57b44ca03eabf0e8b0a6cfddbeaed7961722987678e5cf8d24",
	"sender": "0x36bf2289deb0bAb8382648FCae56ae66d5a1d3fE",
	"signature": "0x91a833387278e5aead139a21cef0a297015ab10ee0f39cd69a9c2df9964339d4342a380e33030109110ee64c3c76fe49c1ffdeff0fcbfd3dbcfe6fd04c070daf1c56442c9a17378f3d4ee835852a16bf28ac5a95058f548993844015aa09379b6a1e6dcf2a750510733c3b6af9e6ddbd6a5b3f8d636c15b1d5d5b3d2dfe50b92e41c000000000000000000000000e8ab863e629a05c73d6a23b99d37027e3763156e000000000000000000000000000000000000000000000000000000000000000001"
}

**Comment by Uxio0** [comment]
Thanks, I was able to reproduce on the tx service:

`POST https://safe-transaction-arbitrum.safe.global/api/v1/safes/0x63B7448D9695Bb595833C9fCd5B3bB5E56F36864/multisig-transactions/`

```json
{
"to": "0x63B7448D9695Bb595833C9fCd5B3bB5E56F36864",
"value": "0",
"data": "0x",
"operation": 0,
"baseGas": "0",
"gasPrice": "0",
"gasToken": "0x0000000000000000000000000000000000000000",
"refundReceiver": "0x0000000000000000000000000000000000000000",
"nonce": "2",
"safeTxGas": "0",
"contractTransactionHash": "0xf24b2f9dc370cb57b44ca03eabf0e8b0a6cfddbeaed7961722987678e5cf8d24",
"sender": "0x36bf2289deb0bAb8382648FCae56ae66d5a1d3fE",
"signature": "0x91a833387278e5aead139a21cef0a297015ab10ee0f39cd69a9c2df9964339d4342a380e33030109110ee64c3c76fe49c1ffdeff0fcbfd3dbcfe6fd04c070daf1c56442c9a17378f3d4ee835852a16bf28ac5a95058f548993844015aa09379b6a1e6dcf2a750510733c3b6af9e6ddbd6a5b3f8d636c15b1d5d5b3d2dfe50b92e41c000000000000000000000000e8ab863e629a05c73d6a23b99d37027e3763156e000000000000000000000000000000000000000000000000000000000000000001"
}
```

**Comment by Uxio0** [comment]
Log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/safe_transaction_service/history/views.py", line 468, in post
    if not serializer.is_valid():
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/app/safe_transaction_service/history/serializers.py", line 220, in validate
    if not safe_signature.is_valid(ethereum_client, safe_address):
  File "/usr/local/lib/python3.10/site-packages/gnosis/safe/safe_signature.py", line 248, in is_valid
    safe_contract.functions.approvedHashes(
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 970, in call
    return call_contract_function(
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 1525, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': ''}
```

**Comment by Uxio0** [comment]
Tried to reproduce it locally, it's working with a public node

**Comment by Uxio0** [comment]
Confirmed, changed the node in production and it's working

**Comment by jonwalch** [comment]
Just tried another signature on the same safe, I got:
1337: {"nonFieldErrors":["Problem connecting to the ethereum node, please try again later"]}

**Comment by Uxio0** [comment]
Should be working now

**Comment by DiogoSoaress** [comment]
@jonwalch I see the transaction was successfully rejected
