### ISSUE TITLE
An unofficial fallback handler is currently set. It can be altered via the Transaction Builder warning on Optimism

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#244]
### Issue Category

Other

### What happened?

User was asking and I'm also seeing this warning in Settings >>Modules >>Fallback handler on Optimism network:

![image](https://github.com/5afe/safe-support/assets/114005210/7e5c0ed9-5d74-419a-9f9e-1b16f8c11be7)

What does this warning mean? Is there any risk for the safe wallet having that warning?

### Date and time this happened or you first noticed this issue

24-07-2023

### Network

Optimism

### Token Type

None

**Comment by liliya-soroka** [comment]
Thank you for the reporting. This is a known issue on the UI and will be fixed in the next release - https://github.com/safe-global/safe-wallet-web/pull/2246

The correct fallback handler is used in the user's safe - https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/compatibility_fallback_handler.json

**Comment by Claire-serveth** [comment]
> Thank you for reporting. This is a known issue on the UI and will be fixed in the next release - [safe-global/safe-wallet-web#2246](https://github.com/safe-global/safe-wallet-web/pull/2246)
> 
> The correct fallback handler is used in the user's safe - https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/compatibility_fallback_handler.json ("10": "0x017062a1dE2FE6b99BE3d9d37841FeD19F573804",)

Thank you @liliya-soroka 🙏 Will relay this to the user and close this issue now.
