### ISSUE TITLE
zkSync - USDT value not reflecting and balance not updated

### ISSUE THREAD

**Issue by inahlikenoother** [5afe/safe-support#314]
### Issue Category

Token balance not up-to-date, in the interface or service

### What happened?

User transferred USDT to Safe, but value is not reflecting and Safe balance is not updated. Asset and balance is reflecting in blockexplorer

![image](https://github.com/5afe/safe-support/assets/114049495/b1a4e08a-1c4e-4afe-8bab-4b10dc4dca29)

### Date and time this happened or you first noticed this issue

25-10-2023

### Network

zkSync

### Safe Address

0xf75A90E3D7B29DC1bb8fea0e9FA0fbC12fe36009

### Token Type

None

### Transactions

```shell
https://explorer.zksync.io/tx/0x4251cc8577c1f29be6a46975de50120f515c6db476e710f0bd7ad16dcc3d75c7
```

**Comment by JagoFigueroa** [comment]
Good morning! Checked with the team and this is not an issue on our end 😢 As you can see the price is not even visible in the explorer [itself](https://explorer.zksync.io/tokenlist) due to the low usage of the token on this chain for now. Maybe there could be some sort of workaround for us to add it in our backend manually in the future but we do not plan to do this for now.

Closing the ticket if that is okay. Cheers!
