### ISSUE TITLE
[Optimism] The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up error while initiating transaction

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#401]
### Issue Category

Transaction execution issue

### What happened?

User is trying to initiate a transfer transaction (USDC) but getting the following errors:
![image](https://github.com/5afe/safe-support/assets/114005210/546130d6-ab10-4b94-b9e4-aed9c1e5a515)

Is this somehow related to blocks being behind on Optimism network?
![image](https://github.com/5afe/safe-support/assets/114005210/3ce906ad-783e-4e94-8825-f825a8d12d00)

Or is this normal behavior for recreated safe addresses on Optimism network? 

(Since user was able to execute transactions successfully for recreated safe address on Polygon network) 

More details:
* User is using Chrome browser, have also tried Brave and Firefox but issue still persists
* Using MetaMask wallet with no other wallet extension installed on the browser
* Have tried to impersonate the account and was able to reproduce the error

Safe wallet: https://app.safe.global/balances?safe=oeth:0xe69F0f444e37E4e7a9068cD79808a90182ab21d0

Additional question, what could be the reason for this error for non-recreated safe addresses?

### Date and time this happened or you first noticed this issue

11-03-2024

### Network

Optimism

### Safe Address

oeth:0xe69F0f444e37E4e7a9068cD79808a90182ab21d0

### Token Type

None

### Transactions

```shell
Link to conversation: https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/shared/all/conversation/212174700006512?view=List
```

**Comment by liliya-soroka** [comment]
@Claire-serveth , thank you for reporting, checking...

**Comment by Claire-serveth** [comment]
Thank you so much @liliya-soroka 🙏

**Comment by liliya-soroka** [comment]
Could we get more details, how the safes were created , please? 
<img width="304" alt="image" src="https://github.com/5afe/safe-support/assets/338622/9438dbcb-81fc-4fee-a079-5c9fde199196">
The safe was created with the wrong mastercopy ( 1.3.0 instead of 1.3.0+L2) - https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe_l2.json. 
So , the error is expected and the app might not work correctly. To transfer funds Safe_CLI is the best way to go as recommended in the message
<img width="355" alt="image" src="https://github.com/5afe/safe-support/assets/338622/f621da7f-61fc-4c9e-b487-ed0cf482dfac">

**Comment by Claire-serveth** [comment]
I see. Yeah, the safe was created through a replay. 
![image](https://github.com/5afe/safe-support/assets/114005210/0fe42a51-2903-4064-9b41-1bb8e3f17cc9)

I also advised the user to use the safe-cli but was also checking if the transaction being delayed might also cause the error. But thank you so much for confirming @liliya-soroka 🙏 I'll inform the user that the only option is to use the safe-cli.
