### ISSUE TITLE
[ETH] Simulation success on tenderly but transaction failed upon execution

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#402]
### Issue Category

Transaction execution issue

### What happened?

User was trying to execute the swap transaction on Uniswap. Although the simulation show successful on tenderly: 
![image](https://github.com/5afe/safe-support/assets/114005210/1c8ebe51-c803-4775-a6f9-380aa8a2dfe7)
![image](https://github.com/5afe/safe-support/assets/114005210/f2cc8643-6b73-49db-8d90-d33b48325dfe)

The transaction did fail upon execution: 
![image](https://github.com/5afe/safe-support/assets/114005210/297f0d0f-7d7d-4806-af13-710adb2b6190)
![image](https://github.com/5afe/safe-support/assets/114005210/d07e79a8-c077-4b14-8a65-595952f779f5)
![image](https://github.com/5afe/safe-support/assets/114005210/c040ff23-6c28-4ea8-9177-51da5a088125)
![image](https://github.com/5afe/safe-support/assets/114005210/71d95576-a7e8-4584-be53-deb1d1520f80)

User was asking for a gas refund for the 2 failed transactions since there was no error shown on the UI during the simulation.

Safe address: https://app.safe.global/transactions/queue?safe=eth:0xD98E489d87a64f41264Ee98B7846294B44C1f72c

### Date and time this happened or you first noticed this issue

11-03-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0xD98E489d87a64f41264Ee98B7846294B44C1f72c

### Token Type

None

### Transactions

```shell
https://etherscan.io/tx/0xd7567207ae9adb0a99ea2beb8167ab43540f9e447009f1ca240c523b6f24579e
https://etherscan.io/tx/0xceb715cc6073ad2f443ef0e90973f753e0b2ec3b3a9ff192bb0a5069cd3bdc36
```

**Comment by johannesmoormann** [comment]
hard to debug a failed swap due to the time-sensitivity of these transactions. better to use Cowswap with enough slippage depending on signature latency. when trying to execute the transaction above, I get the following errors:

<img width="370" alt="Screenshot 2024-03-11 at 15 58 00" src="https://github.com/5afe/safe-support/assets/93598450/69bc0e5e-eeb6-4a58-bf55-457e061685c0">

<img width="579" alt="Screenshot 2024-03-11 at 15 58 04" src="https://github.com/5afe/safe-support/assets/93598450/ad87e106-422e-43a2-a8c1-5326140338f1">

<img width="574" alt="Screenshot 2024-03-11 at 15 58 10" src="https://github.com/5afe/safe-support/assets/93598450/66cc4a8e-cc1b-4621-8e48-09ab357a67a3">

**Comment by Claire-serveth** [comment]
Hi @johannesmoormann thank you so much for the response 🙏 I am able to reproduce this error now because Uniswap has a transaction deadline of 20 or 30 minutes: 
![image](https://github.com/5afe/safe-support/assets/114005210/ec818a74-8cb2-4bbf-88e6-d6cbcdbe96cf)


But earlier, when the transaction on queue is still around 15-17 minutes, there was no error on tenderly earlier as I tried to impersonate the user's account.

**Comment by Claire-serveth** [comment]
> weirdly the successful simulation has a gas limit of 222k vs. the 2x failed EOA transaction having 267k but I am not entirely sure, if we take all signatures into consideration when simulating. need someone with more technical knowledge to look into this.

Thank you so much @johannesmoormann 🙏

**Comment by Claire-serveth** [comment]
User is unresponsive. Will close this issue for now and re-open should there be a need. 🙏
